language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: KuOMpJsUkg2J2BaXFJo45Bk53OrVNQBxjCgMfXVqHA9swiasqjxpkHX07yXGFLKo6UebRgnZgCSBXxUi8eczyRvDnAuQI2gAhgjPyhxW6wz9OQbSOP80vLByLF8Hd4xQspOfJz0KeGttpUfG5J44UEPd/4Bdq0u7VR70YKAYQWg=
  file:
    - build/distributions/xmlcalabash1-plantuml-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
